baseURL: "https://validatedpatterns.io/"
languageCode: "en-us"
title: Validated Patterns
theme: "patternfly"
summaryLength: 20
paginate: 6
params:
  site_logo: /images/validated-patterns.png
security:
  exec:
    allow: ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
    osEnv: (?i)^(GEM_PATH)$

markup:
  asciidocExt:
    attributes: {allow-uri-read, source-highlighter: rouge, icons: font, sectanchors, showtitle}
    safeMode: unsafe
    imagesdir: images
  tableOfContents:
    startLevel: 1
    endLevel: 3
    ordered: false
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  industry: 'industries'
  rh_product: 'rh_products'
  other_product: 'other_products'
  blog_tag: 'blog_tags'
